- id: helmfmt
  name: helmfmt
  description: Runs formatter for helm charts templates code before committing
  entry: helmfmt --files
  language: golang
  types: [file]
  files: templates/.*\.(yaml|yml|tpl)$
